server:
  port: 9999
  servlet:
      context-path: /es
tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 10
    background-processor-delay: 30
spring:
    http:
      encoding:
        force: true
        charset: UTF-8
    application:
        name: elasticsearch-demo
        author: haohao
    data:
        elasticsearch:
          cluster-nodes: 39.96.30.7:9300
          cluster-name: elasticsearch